<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>see_password</name>
   <tag></tag>
   <elementGuidId>52caa227-d478-4238-830f-cbf056cee8a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@alt,'eye')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
